## **NumPy exercises**

Importing Libraries

In [2]:
import sys
import numpy as np

#### Array creation

1.	Create a numpy array of size 10, filled with zeros

In [4]:
zero_array = np.zeros(10)
zero_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2.	Create a numpy array with values ranging from 10 to 49 and set its datatype to float

(Hint: Remember that you can set a specific dtype while defining an array for e.g. 

Arr1 =np.array([1,2,3,4,5]) #defines an int array by default

Arr2 =np.array([1,2,3,4,5], dtype = float) #specifying the dtype as an argument will create a float array). 


In [26]:
arr_1 = np.arange(10,50, dtype=float)
print(arr_1)
print(arr_1.dtype)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49.]
float64


3.	Create a numpy matrix of 2*2 integers, filled with ones.

In [30]:
ones_array = np.ones((2,2), dtype=int)
ones_array

array([[1, 1],
       [1, 1]])

4.	Create a numpy matrix of 3*2 float numbers, filled with ones.

In [32]:
ones_array1 = np.ones((3,2), dtype=float)
ones_array1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

5.	Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones. (#hint: search the function np.ones_like( ) )

In [47]:
x = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]
             ])


ones_arr = np.ones_like(x)
ones_arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

6.	Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros. (hint: similar function as above exists for zeros as well)

In [48]:
x = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]
             ])


ones_arr = np.zeros_like(x)
ones_arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

7.	Create a numpy matrix of 4*4 integers, filled with fives.

In [50]:
fives = np.ones((4,4), dtype=int) * 5
fives

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

8.	Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [51]:
x = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]
             ])


ones_arr = np.ones_like(x) * 7
ones_arr

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

9.	Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [57]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

10.	Create a numpy array, filled with 3 random integer values between 1 and 10.

In [71]:
np.random.randint(1,10, 3)

array([5, 4, 3])

11.	Create a 3* 3 *3 numpy matrix, filled with random float values.

In [78]:
np.random.rand(3,3,3)

array([[[0.71272408, 0.26929485, 0.81880355],
        [0.06671135, 0.56876217, 0.99668926],
        [0.86737397, 0.5601706 , 0.70979156]],

       [[0.39362113, 0.70313078, 0.09609978],
        [0.32442839, 0.87941963, 0.73945019],
        [0.99851178, 0.21482238, 0.05675763]],

       [[0.27509724, 0.75521383, 0.09399604],
        [0.713315  , 0.11576117, 0.40787587],
        [0.31857954, 0.48292166, 0.67538023]]])

12.	Create a numpy array with numbers from 1 to 10

In [80]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

13.	Create a numpy array with the odd numbers between 1 to 10

In [82]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

14.	Create a numpy array with numbers from 1 to 10, in descending order.

In [87]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

15.	Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [92]:
arr = np.arange(9)

reshaped = arr.reshape(3,3)
reshaped

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Array indexing:

1.	Given the X numpy array, show its first element

X = np.array(['A','B','C','D','E'])



In [95]:
X = np.array(['A','B','C','D','E'])
X[0]

'A'

2.	Given the X numpy array, show its last element

X = np.array(['A','B','C','D','E'])


In [96]:
X = np.array(['A','B','C','D','E'])
X[-1]

'E'

3.	Given the X numpy array, show its first three elements

X = np.array(['A','B','C','D','E'])



In [103]:
X = np.array(['A','B','C','D','E'])
X[:3]

array(['A', 'B', 'C'], dtype='<U1')

4.	Given the X numpy array, show all middle elements

X = np.array(['A','B','C','D','E'])



In [107]:
X = np.array(['A','B','C','D','E'])
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

5.	Given the X numpy array, show the elements in reverse position.

X = np.array(['A','B','C','D','E'])


In [108]:
X = np.array(['A','B','C','D','E'])
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

6.	Given the X numpy array, show the elements in an odd position.

X = np.array(['A','B','C','D','E'])


In [112]:
X = np.array(['A','B','C','D','E'])
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

7.	Given the X numpy matrix, show the first row’s elements.


X = np.array([
    
    [1,   2,  3,  4],
    
    [5,   6,  7,  8],
    
    [9,  10, 11, 12],
    
    [13, 14, 15, 16]
])


In [115]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X [0]


array([1, 2, 3, 4])

8.	Given the X numpy matrix, show the last row elements.

X = np.array([
   
    [1,   2,  3,  4],

    [5,   6,  7,  8],
   
    [9,  10, 11, 12],
   
    [13, 14, 15, 16]
])



In [118]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]


array([13, 14, 15, 16])

9.	Given the X numpy matrix, show the first element on first row

X = np.array([

    [1, 2, 3, 4],

    [5, 6, 7, 8],

    [9, 10, 11, 12],

    [13, 14, 15, 16]
])



In [119]:
X = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

X[0,0]

1

10.	Given the X numpy matrix, show the last element on last row.

X = np.array([
    
    [1,   2,  3,  4],
    
    [5,   6,  7,  8],
    
    [9,  10, 11, 12],
    
    [13, 14, 15, 16]
])


In [125]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X [-1,-1]

16

11.	Given the X numpy matrix, show the first two elements on the first two rows.

X = np.array([
    
    [1,   2,  3,  4],
    
    [5,   6,  7,  8],
    
    [9,  10, 11, 12],
    
    [13, 14, 15, 16]
])



In [129]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0:2,0]

array([1, 5])

12.	Given the X numpy matrix, show the last two elements on the last two rows

X = np.array([

    [1,   2,  3,  4],
    
    [5,   6,  7,  8],
    
    [9,  10, 11, 12],
    
    [13, 14, 15, 16]
])




In [133]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:,-1]

array([12, 16])

#### Array manipulation

1.	Convert the given integer numpy array to float (you need to google the function that will help you do this)

X = [-5, -3, 0, 10, 40]


In [142]:
X = np.array([-5, -3, 0, 10, 40])

converted = X.astype(float)
converted

array([-5., -3.,  0., 10., 40.])

2.	Reverse the given numpy array (first element becomes last) through indexing

X = [-5, -3, 0, 10, 40]


In [145]:
X = np.array([-5, -3, 0, 10, 40])
X [::-1]

array([40, 10,  0, -3, -5])

3.	Given the X numpy array, set the fifth element equal to 1

X = np.zeros(10)



In [151]:
X = np.zeros(10)
X [4] = 1
X


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

4.	Given the X numpy matrix, change the last row with all 1

X = np.array([

    [1,   2,  3,  4],
    
    [5,   6,  7,  8],
    
    [9,  10, 11, 12],
    
    [13, 14, 15, 16]
])



In [153]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X [-1] = 1
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

5.	Given the X numpy matrix, add 5 to every element

X = np.array([

    [1,   2,  3,  4],

    [5,   6,  7,  8],

    [9,  10, 11, 12],

    [13, 14, 15, 16]
])


In [154]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X += 5
X 

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])